version: "2"

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: local
      MYSQL_PASSWORD: local_password
    ports:
      - "3306:3306"
    volumes:
      - './mysql:/var/lib/mysql'
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
    depends_on:
      - 'mysql'
volumes:
  mysql:
